django_qgis/projects/urls.py
import os

from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib.auth.decorators import login_required
from django.views.generic import RedirectView

from .views import (
    GroupListView,
    GroupCreateView,
    GroupDetailView,
    GroupUpdateView,
    GroupDeleteView,
    GroupGlobalOptionsView,
    GroupGISProjectListingView,
    WidgetOptionsView,
    ProjectCreateView,
    ProjectDetailView,
    ProjectUpdateView,
    ProjectDeleteView,
    ProjectShowMapView,
    LayerDetailView,
    LayerUpdateView,
    LayerDeleteView,
    WidgetListView,
    WidgetCreateView,
    WidgetDetailView,
    WidgetUpdateView,
    WidgetDeleteView,
    #WidgetLinkView,
    #WidgetUnlinkView,
    QGISRedirectView,
    )


urlpatterns = patterns(
    '',
    # Groups
    url(r'^groups/$', login_required(GroupListView.as_view()), name='group-list'),
    url(r'^groups/add/$', login_required(GroupCreateView.as_view()), name='group-create'),
    url(
        r'^groups/(?P<slug>[-_\w\d]+)/$',
        login_required(GroupDetailView.as_view()),
        name='group-detail'
        ),
    url(
        r'^groups/(?P<slug>[-_\w\d]+)/update/$',
        login_required(GroupUpdateView.as_view()),
        name='group-update'
        ),
    url(
        r'^groups/(?P<slug>[-_\w\d]+)/delete/$',
        login_required(GroupDeleteView.as_view()),
        name='group-delete'
        ),
    url(
        r'^groups/(?P<slug>[-_\w\d]+)/add-project/$',
        login_required(ProjectCreateView.as_view()),
        name='project-create'
        ),
    url(
        r'^groups/(?P<slug>[-_\w\d]+)/GlobalOptions.js$',
        GroupGlobalOptionsView.as_view(),
        name='group-global-options'
        ),
    url(
        r'^groups/(?P<slug>[-_\w\d]+)/GISProjectListing.js$',
        GroupGISProjectListingView.as_view(),
        name='group-gis-project-listing'
        ),
    url(
        r'^projects/widgetoptions/(?P<slug>[-_\w\d]*)$',
        WidgetOptionsView.as_view(),
        name='gis-project-widget-options'
        ),
    # Projects
    url(
        r'^projects/(?P<slug>[-_\w\d]+)/$',
        login_required(ProjectDetailView.as_view()),
        name='project-detail'
        ),
    url(
        r'^projects/(?P<slug>[-_\w\d]+)/update/$',
        login_required(ProjectUpdateView.as_view()),
        name='project-update'
        ),
    url(
        r'^projects/(?P<slug>[-_\w\d]+)/delete/$',
        login_required(ProjectDeleteView.as_view()),
        name='project-delete'
        ),
    url(
        r'^projects/(?P<slug>[-_\w\d]+)/show-map/$',
        ProjectShowMapView.as_view(),
        name='project-show-map'
        ),
    # WARNING: temporary ugly hack, fix it!
    url(
        r'^projects/(?P<slug>[-_\w\d]+)/show-map/(?P<location>.+)',
        QGISRedirectView.as_view()
        ),
    # Layers
    url(
        r'^layers/(?P<slug>[-_\w\d]+)/$',
        login_required(LayerDetailView.as_view()),
        name='layer-detail'
        ),
    url(
        r'^layers/(?P<slug>[-_\w\d]+)/update/$',
        login_required(LayerUpdateView.as_view()),
        name='layer-update'
        ),
    url(
        r'^layers/(?P<slug>[-_\w\d]+)/delete/$',
        login_required(LayerDeleteView.as_view()),
        name='layer-delete'
        ),
    # Widgets
    url(
        r'^widgets/$',
        login_required(WidgetListView.as_view()),
        name='widget-list'
        ),
    url(
        r'^layers/(?P<slug>[-_\w\d]+)/add-widget/$',
        login_required(WidgetCreateView.as_view()),
        name='widget-create'
        ),
    url(
        r'^widgets/(?P<slug>[-_\w\d]+)/$',
        login_required(WidgetDetailView.as_view()),
        name='widget-detail'
        ),
    url(
        r'^widgets/(?P<slug>[-_\w\d]+)/update/$',
        login_required(WidgetUpdateView.as_view()),
        name='widget-update'
        ),
    url(
        r'^widgets/(?P<slug>[-_\w\d]+)/delete/$',
        login_required(WidgetDeleteView.as_view()),
        name='widget-delete'
        ),
    url(
        r'^layers/(?P<slug>[-_\w\d]+)/link/(?P<widgetslug>[-_\w\d]+)$',
        login_required(LayerDetailView.as_view()),
        name='widget-link'
        ),
    url(
        r'^layers/(?P<slug>[-_\w\d]+)/unlink/(?P<widgetslug>[-_\w\d]+)$',
        login_required(LayerDetailView.as_view()),
        name='widget-unlink'
        ),
    )

django_qgis/projects/models.py
import os

from autoslug import AutoSlugField
from django.conf import settings
from django.conf.global_settings import LANGUAGES
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.text import slugify
from django.utils.translation import ugettext, ugettext_lazy as _
from model_utils import Choices
from model_utils.models import TimeStampedModel

from projects.utils.storage import OverwriteStorage
from projects.utils.database import get_database_columns


class Group(TimeStampedModel):
    """A group of projects."""
    UNITS = Choices(
        ('meters', _('Meters')),
        ('feet', _('Feet')),
        ('degrees', _('Degrees')),
        )
    # General info
    name = models.CharField(_('Name'), max_length=255, unique=True)
    title = models.CharField(_('Title'), max_length=255)
    description = models.TextField(_('Description'), blank=True)
    slug = AutoSlugField(
        _('Slug'), populate_from='name', unique=True, always_update=True
        )
    is_active = models.BooleanField(_('Is active'), default=1)
    # l10n
    lang = models.CharField(_('lang'), max_length=20, choices=LANGUAGES)
    # Company logo
    header_logo_img = models.FileField(_('headerLogoImg'), upload_to='logo_img')
    header_logo_height = models.IntegerField(_('headerLogoHeight'))
    header_logo_link = models.URLField(_('headerLogoLink'), blank=True, null=True)
    # Max/min scale
    max_scale = models.IntegerField(_('Max scale'))
    min_scale = models.IntegerField(_('Min scale'))
    # Panoramic max/min scale
    panoramic_max_scale = models.IntegerField(_('Panoramic max scale'))
    panoramic_min_scale = models.IntegerField(_('Panoramic min scale'))
    # Unit of measure
    #units = models.CharField(_('Units'), max_length=255)
    units = models.CharField(_('Units'), choices=UNITS, max_length=255, default=UNITS[0][0])
    # Group SRID (a.k.a. EPSG)
    srid = models.IntegerField(_('SRID/EPSG'))
    # use Google/Bing base maps
    use_commercial_maps = models.BooleanField(_('Use commercial maps'))
    # Company TOS
    header_terms_of_use_text = models.TextField(
        _('headerTermsOfUseText'), blank=True
        )
    header_terms_of_use_link = models.URLField(
        _('headerTermsOfUseLink'), blank=True
        )

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('group-detail', kwargs={'slug': self.slug})


class Project(TimeStampedModel):
    """A QGIS project."""

    def get_project_file_path(instance, filename):
        """Custom name for uploaded project files."""

        group_name = slugify(unicode(instance.group.name))
        project_name = slugify(unicode(instance.title))
        filename = u'%s_%s.qgs' % (group_name, project_name)
        return os.path.join('projects', filename)

    def get_thumbnail_path(instance, filename):
        """Custom name for uploaded thumbnails."""

        group_name = slugify(unicode(instance.group.name))
        project_name = slugify(unicode(instance.title))
        ext = filename.split('.')[-1]
        filename = u'%s_%s.%s' % (group_name, project_name, ext)
        return os.path.join('thumbnails', filename)

    # Project file
    qgis_file = models.FileField(
        _('QGIS project file'),
        upload_to=get_project_file_path,
        storage=OverwriteStorage()
        )

    # General info
    #name = models.CharField(_('Name'), max_length=255)
    title = models.CharField(_('Title'), max_length=255)
    description = models.TextField(_('Description'), blank=True)
    slug = AutoSlugField(
        _('Slug'), populate_from='title', unique=True, always_update=True
        )
    is_active = models.BooleanField(_('Is active'), default=1)

    # Thumbnail
    thumbnail = models.ImageField(
        _('Thumbnail'),
        upload_to=get_thumbnail_path,
        storage=OverwriteStorage(),
        blank=True,
        null=True
        )

    # Group
    group = models.ForeignKey(Group, verbose_name=_('Group'))
    
    # Extent
    initial_extent = models.CharField(_('Initial extent'), max_length=255)
    max_extent = models.CharField(_('Max extent'), max_length=255)

    # Whether current project acts as a panoramic map within group
    is_panoramic_map = models.BooleanField(_('Is panoramic map'), default=0)

    class Meta:
        unique_together = (('title', 'group'))

    def __unicode__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('project-detail', kwargs={'slug': self.slug})

    def get_absolute_path(self):
        """Get absolute filesystem path of project file.

        WARNING: we are using this inside a template
        (``GlobalOptions.js``), so that filesystem path is publicly
        revealed. That can be a security breach. Fix it!
        """

        return os.path.join(settings.MEDIA_ROOT, self.qgis_file.name)
		
    def get_absolute_path_to_project_filepath(self):
        return os.path.join(settings.MEDIA_ROOT,self.filepath())

    def get_initial_extent_list(self):
        """Get initial extent string as a list of values."""

        return self.initial_extent.split(';')

    def filepath(self):
        """Get path of related file.

        Eg: ``projects/`` instead of ``projects/helloworld.qgs``
        """
        
        return os.path.dirname(self.qgis_file.name)

    def filename(self):
        """Get related filename without path.

        Eg: ``helloworld.qgs`` instead of ``projects/helloworld.qgs``
        """
        
        return os.path.basename(self.qgis_file.name)

    def filename_without_ext(self):
        """Get related filename without path and without extension.

        Eg: ``helloworld`` instead of ``projects/helloworld.qgs``
        """

        return os.path.splitext(self.filename())[0]

    def thumbname(self):
        return os.path.basename(self.thumbnail.name)

    def get_visible_layers(self):
        return self.layer_set.filter(is_visible=True)

    def save(self, *args, **kwargs):
        """Custom save method."""

        # Set a default max_extent
        if not self.max_extent:
            self.max_extent = self.initial_extent
        # At most one "map" project per group
        if self.is_panoramic_map:
            try:
                temp = Project.objects.get(
                    is_panoramic_map=True, group=self.group
                    )
            except Project.DoesNotExist:
                pass
            else:
                if temp != self:
                    temp.is_panoramic_map = False
                    temp.save()
        super(Project, self).save(*args, **kwargs)


class Widget(models.Model):
    """A search widget."""

    TYPES = Choices(
        #('hyperlink', _('Hyperlink')),
        ('search', _('Search')),
        ('tooltip', _('Tooltip')),
        )
    name = models.CharField(_('Name'), max_length=255)
    body = models.TextField(_('Body'))
    datasource = models.TextField(_('datasource'))
    widget_type = models.CharField(_('Type'), choices=TYPES, max_length=255)
    slug = AutoSlugField(
        _('Slug'), populate_from='name', unique=True, always_update=True
        )

    def __unicode__(self):
        return self.name


class Layer(models.Model):
    """A QGIS layer."""

    TYPES = Choices(
        ('postgres', _('Postgres')),
        ('spatialite', _('SpatiaLite')),
        ('wfs', _('WFS')),
        ('wms', _('WMS')),
        ('ogr', _('OGR')),
        ('gdal', _('GDAL')),
        )
    # General info
    name = models.CharField(_('Name'), max_length=255)
    title = models.CharField(_('Title'), max_length=255, blank=True)
    description = models.TextField(_('Description'), blank=True)
    slug = AutoSlugField(
        _('Slug'), populate_from='name', unique=True, always_update=True
        )
    is_active = models.BooleanField(_('Is active'), default=1)
    # Project
    project = models.ForeignKey(Project, verbose_name=_('Project'))
    # Type and content
    layer_type = models.CharField(_('Type'), choices=TYPES, max_length=255)
    datasource = models.TextField(_('Datasource'))
    is_visible = models.BooleanField(_('Is visible'), default=1)
    order = models.IntegerField(_('Order'),default=1)
    # Optional data file (non-postgres layers need it)
    data_file = models.FileField(
        _('Associated data file'),
        upload_to='data-files',
        blank=True,
        null=True
        )
    # Database columns (postgres layers need it)
    database_columns = models.TextField(_('Database columns'), blank=True)
    # Widgets
    widgets = models.ManyToManyField(
        Widget,
        verbose_name=_('Widgets'),
        through='LayerWidget',
        blank=True,
        null=True
        )

    def __unicode__(self):
        return self.name

    class Meta:
        unique_together = (('name', 'project',),)
        ordering = ['order']

    def get_absolute_url(self):
        return reverse('layer-detail', kwargs={'slug': self.slug})

    def needs_data_file(self):
        """Whether a data file is needed for current layer."""

        if self.layer_type != self.TYPES.postgres and not self.data_file:
            return True

    def set_database_columns(self):
        """Get database columns and set the relative layer field."""

        if self.layer_type == self.TYPES.postgres:
            self.database_columns = get_database_columns(self.datasource)
            self.save()


class LayerWidget(models.Model):
    """A widget for a layer."""

    widget = models.ForeignKey(Widget, verbose_name=_('Widget'))
    layer = models.ForeignKey(Layer, verbose_name=_('Layer'))
    #alias = models.CharField(_('Alias'), max_length=255, blank=True)

    def __unicode__(self):
        return "%s - %s" % (self.widget.name,self.layer.name)
    

django_qgis/projects/templates/projects/base_confirm_delete.html
{% load i18n%}
<h1>
  {%if object.name %}
  	{{ object.name }}
  {% else %}
  	{{ object.title }}
  {% endif %}
  <br />
  {%if object.name %}
  	{{ object.title }}
  {% endif %}
  <small></small>
</h1>

<hr>
<p>{%trans 'Are you sure you want to delete this item? All related items will be deleted too.'%}</p>
<form action="" method="post">
  {% csrf_token %}
  <input type="hidden" name="post" value="yes" />
  <input class="btn btn-primary" type="submit" value="{%trans "Yes, I'm sure"%}" />
</form>
<hr>

django_qgis/projects/templates/projects/group_confirm_delete.html
{% extends 'base.html' %}
{% load i18n%}
{% block nav-projects %}active{% endblock %}

{% block breadcrumbs %}
<ul class="breadcrumb">
  <li>
    <a href="{% url 'home' %}">{%trans 'Home'%}</a>
  </li>
  <li>
    <a href="{% url 'group-list' %}">{%trans 'Maps'%}</a>
  </li>
  <li>
    <a href="{% url 'group-detail' object.slug %}">{{ object.name }}</a>
  </li>
  <li class="active">{%trans 'Remove'%}</li>
</ul>
{% endblock %}

{% block content %}
{% include 'projects/base_confirm_delete.html' %}
{% endblock content %}

django_qgis/projects/templates/projects/group_detail.html
{% extends 'base.html' %}
{% load i18n%}
{% block nav-projects %}active{% endblock %}

{% block breadcrumbs %}
<ul class="breadcrumb">
  <li>
    <a href="{% url 'home' %}">{%trans 'Home'%}</a>
  </li>
  <li>
    <a href="{% url 'group-list' %}">{%trans 'Maps'%}</a>
  </li>
  <li class="active">{{ object }}</li>
</ul>
{% endblock %}

{% block content %}
<h1>
  <span class="pull-right">
    <a class="btn btn-warning" href="{% url 'group-update' object.slug %}">
      <i class="glyphicon glyphicon-pencil"></i> {%trans 'Edit'%}
    </a>
    <a class="btn btn-danger" href="{% url 'group-delete' object.slug %}">
      <i class="glyphicon glyphicon-remove"></i> {%trans 'Remove'%}
    </a>
  </span>
  {{ object.name }}
  <br />
  <small>{{ object.title }}</small>
</h1>
<hr>
{% if object.description %}

<div class="well">
  <p>
    <h4>In questa sezione si visualizzano le specifiche del gruppo tematico e si gestiscono i progetti cartografici associati</h4>
    <ul class="unstyled">
    <li>Per visualizzare le specifiche del singolo progetti cliccare sul <strong>nome del progetto</strong> o sul relativo link <strong>"Dettaglio"</strong></li>
    <li>Per modificare le specifiche del singolo progetto cliccare sul relativo link <strong>"Modifica"</strong></li>
    <li>Per visualizzare la mappa relativa al singolo progetto cliccare sul relativo link <strong>"Visualizza la mappa"</strong></li>
    <li>Per aggiungere un nuovo progetto cartografico al gruppo cliccare sul tasto <strong>"Nuovo progetto"</strong></li>
    </ul>
  </p>
</div>

<div class="well">
    <h3>{%trans 'Cartographic project description'%}</h3>
  {{ object.description }}
</div>

{% endif %}
<div class="row">
  <div class="col-md-6">
  <h3>{%trans 'Geografic component'%}</h3>
    <ul class="list-unstyled">
      <li><h4>{%trans 'Geographic coordinate system'%}</h4>
      <li><strong>{%trans 'SRID'%}</strong>: {{ object.srid }}</li>
      <li><strong>{%trans 'Units'%}</strong>: {{ object.units }}</li>
      <li><h4>{%trans 'Principal map'%}</h4>
      <li><strong>{%trans 'Max scale'%}</strong>: {{ object.max_scale }}</li>
      <li><strong>{%trans 'Min scale'%}</strong>: {{ object.min_scale }}</li>
      <li><h4>{%trans 'Overview Map'%}</h4>
      <li><strong>{%trans 'Panoramic max scale'%}</strong>: {{ object.panoramic_max_scale }}</li>
      <li><strong>{%trans 'Panoramic min scale'%}</strong>: {{ object.panoramic_min_scale }}</li>
    </ul>
  </div>
  <div class="col-md-6">
  <h3>{%trans 'Interface component'%}</h3>
    <ul class="list-unstyled">
      <li><h4>{%trans 'Interface language'%}</h4>
      <li><strong>{%trans 'Language'%}</strong>: {{ object.lang }}</li>
      <li><h4>{%trans 'Associated logo'%}</h4>
      <li><strong>{%trans 'HeaderLogoImg'%}</strong>:
        {% if object.header_logo_img %}
	<br />
        <img style="height: 120px;" src="{{ MEDIA_URL }}{{ object.header_logo_img }}" />
        {% else %}
        Not set
        {% endif %}
      </li>
      <li><strong>{%trans 'HeaderLogoHeight'%}</strong>: {{ object.header_logo_height }}</li>
      <li><strong>{%trans 'HeaderLogoLink'%}</strong>: {{ object.header_logo_link }}</li>
      <li><h4>{%trans 'Terms of use'%}</h4>
      <li><strong>{%trans 'HeaderTermsOfUseText'%}</strong>:{{ object.header_terms_of_use_text }}</li>
      <li><strong>{%trans 'HeaderTermsOfUseLink'%}</strong>: {{ object.header_terms_of_use_link }}</li>
    </ul>
  </div>
</div>
<hr>
<h2>
  {%trans 'Projects'%}
  <span class="pull-right">
    <a class="btn btn-primary" href="{% url 'project-create' object.slug %}">
      <i class="glyphicon glyphicon-plus"></i> {%trans 'New project'%}
    </a>
  </span>
</h2>
<form id="set-project-as-group-map-form" action="" method="post">
  {% csrf_token %}
  <table class="table table-striped table-condensed">
    <tr>
      <th>{%trans 'Thumbnail'%}</th>
      <th>{%trans 'Title'%}</th>
      <th>{%trans 'Is panoramic map'%}</th>
      <th class="text-right">{%trans 'Admin'%}</th>
    </tr>
    {% for project in group.project_set.all %}
    <tr>
      <td>
        <a href="{% url 'project-detail' project.slug %}">
          {% if project.thumbnail %}
          <img style="height: 60px;" src="{{ MEDIA_URL }}{{ project.thumbnail }}" />
          {% else %}
          <img src="http://placehold.it/80x60" />
          {% endif %}
      </td>
      <td><a href="{% url 'project-detail' project.slug %}">{{ project.title }}</a></td>
      <td><input type="radio" value="{{ project.slug }}" name="set-project-as-group-map"{% if project.is_panoramic_map %} checked{% endif %} /></td>
      <td class="text-right">
        <a class="btn btn-primary btn-sm" href="{% url 'project-show-map' project.slug %}?map={{ MEDIA_ROOT }}{{ project.qgis_file }}" target="_blank"><i class="glyphicon glyphicon-globe"></i> {%trans 'View map'%}</a> 
        <a class="btn btn-info btn-sm" href="{% url 'project-detail' project.slug %}"><i class="glyphicon glyphicon-info-sign"></i> {%trans 'Detail'%}</a>
        <a class="btn btn-warning btn-sm" href="{% url 'project-update' project.slug %}"><i class="glyphicon glyphicon-pencil"></i> {%trans 'Edit'%}</a> 
        <a class="btn btn-danger btn-sm" href="{% url 'project-delete' project.slug %}"><i class="glyphicon glyphicon-remove"></i> {%trans 'Remove'%}</a>
      </td>
    </tr>
    {% endfor %}
    <tr>
      <th></th>
      <th></th>
      <th></th>
      <th><input class="btn btn-default" type="submit" value="{%trans 'Set panoramic map'%}" /></th>
      <th></th>
    </tr>
  </table>
</form>
{% endblock content %}

django_qgis/projects/templates/projects/group_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load i18n%}

{% block nav-projects %}active{% endblock %}

{% block breadcrumbs %}
<ul class="breadcrumb">
  <li>
    <a href="{% url 'home' %}">{%trans 'Home'%}</a>
  </li>
  <li>
    <a href="{% url 'group-list' %}">{%trans 'Maps'%}</a>
  </li>
  {% if view.object %}
  <li>
    <a href="{% url 'group-detail' object.slug %}">{{ view.object.name }}</a>
  </li>
  <li class="active">{%trans 'Edit'%}</li>
  {% else %}
  <li class="active">{%trans 'Add group'%}</li>
  {% endif %}
</ul>
{% endblock %}

{% block content %}
{% if view.object %}
<h1>{{ view.object.name }}<br /><small>{{ view.object.title }}</small></h1>
{% else %}
<h1>Add group</h1>
{% endif %}
<hr>

<form enctype="multipart/form-data" action="." method="post" role="form">
  {% csrf_token %}
  {# form|crispy #}
  {%crispy form%}
  <hr>
  <input class="btn btn-primary" type="submit" value="{%trans 'Save'%}" />
</form>
{% endblock content %}

django_qgis/projects/templates/projects/group_list.html
{% extends 'base.html' %}
{% load i18n%}

{% block nav-projects %}active{% endblock %}

{% block breadcrumbs %}
<ul class="breadcrumb">
  <li>
    <a href="{% url 'home' %}">{% trans 'Home' %}</a>
  </li>
  <li class="active">{%trans 'Maps'%}</li>
</ul>
{% endblock %}

{% block content %}
<h1>
  {%trans 'Maps'%}<br />
  <small>{%trans 'Manage your maps'%}</small>
</h1>
<hr>
<div class="row">
<div class="col-md-12">
	<div class="well small">
	  <p>
	    <h4>In questa sezione è possibile visualizzare la lista dei gruppi tematici di cartografie presenti, gestirli e crearne di nuovi</h4>
	    <ul class="list-unstyled">
	    <li>Per visualizzare le specifiche dei singoli gruppi cliccare sul <strong>nome del gruppo</strong> o sul relativo link <strong>"Dettaglio"</strong></li>
	    <li>Per modificare le specifiche dei singoli gruppi cliccare sul relativo link <strong>"Modifica"</strong></li>
	    <li>Per aggiungere un nuovo gruppo tematico cliccare sul tasto <strong>"Nuovo gruppo"</strong></li>
	    </ul>
	  </p>
	</div>
<hr>
<!-- </div> -->
<!-- <div class="col-md-8"> -->
<h2>
  <span class="pull-right">
    <a class="btn btn-primary" href="{% url 'group-create' %}">
      <i class="glyphicon glyphicon-plus"></i> {%trans 'New group'%}
    </a>
  </span>
  {%trans 'Groups' %}
</h2>
<table class="table table-striped table-condensed">
</div>
  <tr>
    <th>{%trans 'Thumbnail'%}</th>
    <th>{%trans 'Name'%}</th>
    <th>{%trans 'Title'%}</th>
    <th class="text-right">{%trans 'Admin'%}</th>
  </tr>
  {% for object in object_list %}
  <tr>
      <td>
          <img style="height: 60px;" src="{{ MEDIA_URL }}{{ object.header_logo_img }}" />
      </td>
    <td><a href="{% url 'group-detail' object.slug %}">{{ object.name }}</a></td>
    <td>{{ object.title }}</td>
    <td class="text-right">
      <a class="btn btn-info btn-sm" href="{% url 'group-detail' object.slug %}"><i class="glyphicon glyphicon-info-sign"></i> {%trans 'Detail'%}</a> 
      <a class="btn btn-warning btn-sm"  href="{% url 'group-update' object.slug %}"><i class="glyphicon glyphicon-pencil"></i> {%trans 'Edit'%}</a>  
      <a class="btn btn-info btn-danger btn-sm"  href="{% url 'group-delete' object.slug %}"><i class="glyphicon glyphicon-remove"></i> {%trans 'Remove'%}</a> 
    </td>
  </tr>
  {% endfor %}
</table>
</div> <!--  close row -->
{% endblock content %}

django_qgis/projects/templates/projects/layer_confirm_delete.html
{% extends 'base.html' %}
{% load i18n%}
{% block nav-projects %}active{% endblock %}

{% block breadcrumbs %}
<ul class="breadcrumb">
  <li>
    <a href="{% url 'home' %}">{% trans 'Home' %}</a>
  </li>
  <li>
    <a href="{% url 'group-list' %}">{% trans 'Maps' %}</a>
  </li>
  <li>
    <a href="{% url 'group-detail' object.project.group.slug %}">{{ object.project.group.name }}</a>
  </li>
  <li>
    <a href="{% url 'project-detail' object.project.slug %}">{{ object.project.name }}</a>
  </li>
  <li>
    <a href="{% url 'layer-detail' object.slug %}">{{ object.name }}</a>
  </li>
  <li class="active">{% trans 'Remove' %}</li>
</ul>
{% endblock %}

{% block content %}
{% include 'projects/base_confirm_delete.html' %}
{% endblock content %}

django_qgis/projects/templates/projects/project_confirm_delete.html
{% extends 'base.html' %}
{% load i18n%}

{% block nav-projects %}active{% endblock %}

{% block breadcrumbs %}
<ul class="breadcrumb">
  <li>
    <a href="{% url 'home' %}">{% trans 'Home' %}</a>
  </li>
  <li>
    <a href="{% url 'group-list' %}">{% trans 'Maps' %}</a>
  </li>
  <li>
    <a href="{% url 'group-detail' object.group.slug %}">{{ object.group.name }}</a>
  </li>
  <li>
    <a href="{% url 'project-detail' object.slug %}">{{ view.object.title }}</a>
  </li>
  <li class="active">{% trans 'Remove' %}</li>
</ul>
{% endblock %}

{% block content %}
{% include 'projects/base_confirm_delete.html' %}
{% endblock content %}